version: 2.5.{build}
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2022
configuration: Release
platform:
- x86
- x64
only_commits:
  files:
    - apis_def/*
    - '**/*.h'
    - '**/*.cpp'
    - '**/*.rc'
    - '**/*.vcxproj'
build_script:
- cmd: >-
    msbuild.exe xAnalyzer.sln /verbosity:minimal /t:Build /p:Configuration=Release;Platform=Win32

    msbuild.exe xAnalyzer.sln /verbosity:minimal /t:Build /p:Configuration=Release;Platform=x64
artifacts:
- path: bin\x32\xAnalyzer.dp32
  name: xAnalyzer.dp32
- path: bin\x64\xAnalyzer.dp64
  name: xAnalyzer.dp64
- path: apis_def
  name: apis_def
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: xAnalyzer x86x64
  auth_token:
    secure: ej6yAWoBcT7Nqu0HWnOgyUmXssO03/sYwjW5HIYuRi13rll5mVgJO3VzSUEG4wS4
  artifact: xAnalyzer.dp32,xAnalyzer.dp64,apis_def
notifications:
- provider: Email
  to:
  - yunietps@yahoo.com
  subject: AppVeyor New Build Notice
  message: A new build has been placed in GitHub for xAnalyzer
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
