version: 2.3.{build}
skip_tags: true
image: Visual Studio 2013
configuration: Release
platform:
- x86
- x64
only_commits:
  files:
    - apis_def/*
    - '**/*.h'
    - '**/*.cpp'
    - '**/*.rc'
build_script:
- cmd: >-
    msbuild.exe xAnalyzer.sln /verbosity:minimal /t:Build /p:Configuration=Release;Platform=Win32
    msbuild.exe xAnalyzer.sln /verbosity:minimal /t:Build /p:Configuration=Release;Platform=x64
artifacts:
- path: bin\x32\xAnalyzer.dp32
  name: xAnalyzer.dp32
- path: bin\x64\xAnalyzer.dp64
  name: xAnalyzer.dp64
- path: apis_def
  name: apis_def
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: xAnalyzer x86x64
  auth_token:
    secure: e0tpvY9RhIn1LUvJjU0ast63hPNRCuXk/PbmXengsaugqMIm3a+2CSh/vGFbZDC/
  artifact: xAnalyzer.dp32,xAnalyzer.dp64,apis_def
notifications:
- provider: Email
  to:
  - yunietps@yahoo.com
  subject: AppVeyor New Build Notice
  message: A new build has been placed in GitHub for xAnalyzer
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
